// Which campus place is which OSM feature.
//
// Every entry needs evidence: either the official plan number plus the OSM
// feature, or a coordinate published by the previous maintainer, or an
// OpenStreetMap name tag. `position` says how much of that survives into the
// map:
//   footprint  — OSM area geometry, drawn as a building and used as pin anchor
//   node       — OSM has only a point for this place; pin is drawn there
//   unverified — no defensible position; listed for event filtering only
export const venueConfig = [
  {
    id: 'akm',
    name: 'Atatürk Kültür ve Sanat Merkezi',
    shortName: 'AKM',
    osm: 'way/374982336',
    plan: 5,
    position: 'footprint',
    style: 'culture',
    color: '#e5a566',
    aliases: ['Atatürk Kültür ve Sanat Merkezi', 'AKM', 'Anadolu Üniversitesi Atatürk Kültür ve Sanat Merkezi', 'Opera ve Bale Salonu', 'Oda Tiyatrosu Salonu', 'Oda Konseri Salonu', 'Uygulama Sahnesi'],
    evidence: 'OSM name tag matches; handoff centre 39.791214/30.499968 is the mean of this way\'s nodes (0.1 m). Official AKM page lists its four halls.',
  },
  {
    id: 'ogrenci-merkezi',
    name: 'Öğrenci Merkezi',
    shortName: 'Öğrenci Merkezi',
    osm: 'way/374982357',
    plan: 49,
    position: 'footprint',
    style: 'culture',
    color: '#83b1b2',
    aliases: ['Öğrenci Merkezi', 'Yunus Emre Salonu', 'Salon 2009', 'Salon 2016', 'Farabi Salonu', 'Nasrettin Hoca Salonu', 'Fuaye Alanı', 'Öğrenci Merkezi Yunus Emre Salonu', 'Öğrenci Merkezi Nasrettin Hoca Salonu', 'Öğrenci Merkezi Fuaye Alanı', 'Öğrenci Merkezi Yunus Emre Salonu ve Fuaye Alanı', 'Öğrenci Merkezi Nasrettin Hoca Salonu ve Fuaye Alanı', 'ğrenci Merkezi Yunus Emre Salonu', 'Öğrenci Mrekezi Yunus Emre Salonu', 'Şener Şen Kültür Salonu'],
    evidence: 'OSM name tag matches; handoff centre is the mean of this way\'s nodes. Official pages place Yunus Emre Salonu (368) and Nasrettin Hoca Salonu / Salon 2009 (265) in this building.',
  },
  {
    id: 'kutuphane',
    name: 'Kütüphane ve Dokümantasyon Merkezi',
    shortName: 'Kütüphane',
    osm: 'way/761605589',
    plan: 40,
    position: 'footprint',
    style: 'civic',
    color: '#9ab9a5',
    aliases: ['Kütüphane', 'Kütüphane ve Dokümantasyon Merkezi'],
    evidence: 'OSM name tag "Kütüphane"; handoff centre is the mean of this way\'s nodes.',
  },
  {
    id: 'sinema',
    name: 'Sinema Anadolu',
    shortName: 'Sinema',
    osm: 'way/374187005',
    plan: 54,
    position: 'footprint',
    style: 'culture',
    color: '#d98c8f',
    aliases: ['Sinema Anadolu', 'Sinema Anadolu Önü', 'Sinema Anadolu Sokak', 'Sinema Anadolu Sokağı'],
    evidence: 'OSM name tag matches; handoff centre is the mean of this way\'s nodes. Official page: 395 seats. The event feed also names the open-air stand area in front of the building ("Sinema Anadolu Sokak"), which is no building of its own, so those events land on the cinema.',
  },
  {
    id: 'cagdas-muze',
    name: 'Çağdaş Sanatlar Müzesi',
    shortName: 'Sanat Müzesi',
    osm: 'way/374986688',
    plan: 14,
    position: 'footprint',
    style: 'historic',
    color: '#daa9b1',
    aliases: ['Çağdaş Sanatlar Müzesi'],
    evidence: 'OSM name tag matches. Official museum page: single-storey, rectangular, yellow-white facade, formerly a barracks building.',
  },
  {
    id: 'emyo',
    name: 'Eskişehir Meslek Yüksekokulu',
    shortName: 'EMYO',
    osm: 'way/660042188',
    plan: 24,
    position: 'footprint',
    style: 'faculty',
    color: '#a2bb9b',
    aliases: ['Eskişehir Meslek Yüksekokulu', 'Adili Sadık Bahçe Seminer Salonu'],
    evidence: 'OSM name tag "Eskişehir Meslek Yüksek Okulu", building:levels=2; handoff centre is the mean of this way\'s nodes.',
  },
  {
    id: 'biltek-myo',
    name: 'Bilişim Teknolojileri Meslek Yüksekokulu',
    shortName: 'Bilişim MYO',
    osm: 'way/667918876',
    plan: null,
    position: 'footprint',
    style: 'faculty',
    color: '#8fa8bb',
    aliases: ['Bilişim Teknolojileri Meslek Yüksekokulu', 'Bilişim Teknolojileri Meslek Yüksekokulu Konferans Salonu', 'Bilişim Bloğu'],
    evidence: 'OSM way/667918876 "Bilişim Bloğu" (building=school, building:levels=4, addr:street Anadolu Üniversitesi) is the information-technology block. The university event feed names the hall inside it "Bilişim Teknolojileri Meslek Yüksekokulu Konferans Salonu", so that name maps here; the plan carries no verified number for the block.',
  },
  {
    id: 'turizm',
    name: 'Turizm Fakültesi',
    shortName: 'Turizm',
    osm: 'way/374262148',
    plan: 61,
    position: 'footprint',
    style: 'faculty',
    color: '#a8b6ca',
    aliases: ['Turizm Fakültesi', 'Turizm Fakültesi Amfi-1 ve 3'],
    evidence: 'OSM name tag matches; handoff centre is the mean of this way\'s nodes.',
  },
  {
    id: 'hukuk',
    name: 'Hukuk Fakültesi',
    shortName: 'Hukuk',
    osm: 'way/374591223',
    plan: 27,
    position: 'footprint',
    style: 'faculty',
    color: '#b9a58f',
    aliases: ['Hukuk Fakültesi', 'Hukuk Fakültesi Amfi-1'],
    evidence: 'OpenStreetMap labels this footprint "Yabancı Diller Yüksekokulu-2", which is a wrong label rather than a second building: the OSM node node/11450099269 inside the block is named "Anadolu Üniversitesi Hukuk Fakültesi" (amenity=school, operator "Anadolu Üniversitesi Hukuk Fakültesi Dekanlığı ve Rektörlüğü") and the official plan\'s number 27 falls 29 m from the same footprint. The map follows the node and the plan.',
  },
  {
    id: 'egitim',
    name: 'Eğitim Fakültesi',
    shortName: 'Eğitim',
    osm: 'relation/5563680',
    plan: 22,
    position: 'footprint',
    style: 'faculty',
    color: '#aabcb8',
    aliases: ['Eğitim Fakültesi', 'Eğitim Fakültesi E-Blok Konferans Salonu'],
    evidence: 'OSM multipolygon relation "Eğitim Fakültesi A - B - C Blok" (university, addr:street Anadolu Üniversitesi) is 15 m from the official plan\'s number 22 marker; official plan lists number 22 as Eğitim Fakültesi A–E Blok.',
  },
  {
    id: 'eczacilik',
    name: 'Eczacılık Fakültesi',
    shortName: 'Eczacılık',
    osm: 'relation/5563679',
    plan: 18,
    position: 'footprint',
    style: 'faculty',
    color: '#b7c4a8',
    aliases: ['Eczacılık Fakültesi', 'Eczacılık Fakültesi Lokali'],
    evidence: 'OSM multipolygon relation "Eczacılık Fakültesi" is inside the campus boundary; the official plan numbers 18 and 19 (faculty and its lounge) sit in the same western block and the Tepebaşı–Eczacılık gate is named after it.',
  },
  {
    id: 'kongre',
    name: 'Kongre Merkezi',
    shortName: 'Kongre',
    osm: 'way/374591227',
    plan: 38,
    position: 'footprint',
    style: 'culture',
    color: '#b4a1d4',
    aliases: ['Kongre Merkezi', 'Salon Anadolu', 'Kırmızı Salon', 'Mavi Salon'],
    evidence: 'The official plan draws numbers 38 (Kongre Merkezi) and 45 (Anadolu Konukevi) on the same block, the plan marker for 38 falls 22 m from this footprint\'s centre, and the Lisansüstü Eğitim Enstitüsü gives its official address as "Kongre Merkezi Binası, Yunus Emre Kampüsü" (https://www.anadolu.edu.tr/akademik/enstituler/2113/lisansustu-egitim-enstitusu/iletisim-bilgileri). OpenStreetMap labels the outline "Otel Anadolu" (tourism=hotel) after the guesthouse the block also houses, so the name tag alone was misleading; the plan and the university address place the congress centre here. Official page: Salon Anadolu 251, Kırmızı 130, Mavi 88.',
  },
  {
    id: 'salon-2003',
    name: 'Salon 2003 (Koral Çalgan Salonu)',
    shortName: 'Salon 2003',
    osm: null,
    plan: 53,
    position: 'unverified',
    style: 'culture',
    color: '#bca98a',
    aliases: ['Salon 2003', 'Koral Çalgan Salonu'],
    evidence: 'Salon 2003 is the same hall as Koral Çalgan Salonu (renamed in October 2019, e-Gazete). The plan puts number 53 at [-188, 314], north of Teknopark, where OSM has only unnamed small buildings; the nearest named block is relation/5563046 ("Yunus Emre Sağlık Hizmetleri Meslek Yüksekokulu"), but that wing could not be verified as the hall, so no pin is drawn.',
  },
  {
    id: 'yemekhane',
    name: 'Yemekhane',
    shortName: 'Yemekhane',
    osm: 'way/275001635',
    plan: null,
    position: 'footprint',
    style: 'civic',
    color: '#c3b18d',
    aliases: ['Yemekhane'],
    evidence: 'OSM name tag "Yemekhane", building:levels=2.',
  },
  {
    id: 'yeni-yemekhane',
    name: 'Yeni Yemekhane',
    shortName: 'Yeni Yemekhane',
    osm: 'way/1119929972',
    plan: null,
    position: 'footprint',
    style: 'civic',
    color: '#c8b696',
    aliases: ['Yeni Yemekhane', 'Yeni Yemekhane Önü', 'Yeni Yemekhane ve Sinema Anadolu Önü'],
    evidence: 'OSM name tag "Anadolu Üniversitesi Yeni Yemekhane".',
  },
  {
    id: 'cami',
    name: 'Anadolu Üniversitesi Camii',
    shortName: 'Cami',
    osm: 'way/718618164',
    plan: null,
    position: 'footprint',
    style: 'religious',
    color: '#cdd6c4',
    aliases: ['Anadolu Üniversitesi Camii', 'Anadolu Üniversitesi Camii Bahçesi'],
    evidence: 'OSM building=mosque inside campus; no name tag, so the name is the university\'s own and the footprint is the evidence.',
  },
  {
    id: 'kyk-bankamatikler',
    name: 'KYK ve Bankamatikler Önü',
    shortName: 'KYK ve Bankamatikler',
    osm: 'way/374982346',
    plan: 11,
    position: 'footprint',
    style: 'outdoor',
    color: '#c9b27f',
    aliases: ['KYK ve Bankamatikler Önü', 'KYK ve Bankamatikler'],
    evidence: 'The square in front of the KYK dormitories, where the campus ATMs stand (Ziraat Bankası ATM node/10052862752, 39.7912163/30.5027838). The official plan numbers 11 (ATM gişeleri) and 39 (KYK yurtları): the ATMs are the venue and the dormitory block way/374982346 ("KYK Öğrenci Yurtları", building=dormitory) is its anchor, so the footprint is drawn.',
  },
];
